import AppKit
import Combine
import ServiceManagement
import SwiftUI

@MainActor
final class ClipboardStore: ObservableObject {
    @Published private(set) var items: [ClipItem] = [] {
        didSet { scheduleSave() }
    }
    /// Selected item ids, in the order they were clicked.
    @Published private(set) var selection: [UUID] = []
    @Published var query = "" {
        didSet { highlightedID = visibleItems.first?.id }
    }
    @Published var highlightedID: UUID?
    @Published var toast: String?
    @Published private(set) var openToken = 0
    @Published var separator: JoinSeparator {
        didSet { UserDefaults.standard.set(separator.rawValue, forKey: "separator") }
    }
    @Published var launchAtLogin: Bool = SMAppService.mainApp.status == .enabled
    @Published var pasteAfterCopy: Bool {
        didSet { UserDefaults.standard.set(pasteAfterCopy, forKey: "pasteAfterCopy") }
    }
    @Published var retention: Retention {
        didSet {
            UserDefaults.standard.set(retention.rawValue, forKey: "retention")
            pruneExpired()
        }
    }

    var onRequestClose: (() -> Void)?
    /// Closes the popover and pastes into the app that was in front before it opened.
    var onRequestPaste: (() -> Void)?

    private let maxItems = 200
    private let maxImageBytes = 8 * 1024 * 1024
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private var saveWork: DispatchWorkItem?
    private var thumbnails: [UUID: NSImage] = [:]
    private var appIcons: [String: NSImage] = [:]
    private var lastTap: (id: UUID, time: Date, selectionBefore: [UUID])?

    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
    ]

    init() {
        separator = JoinSeparator(rawValue: UserDefaults.standard.string(forKey: "separator") ?? "") ?? .nothing
        pasteAfterCopy = UserDefaults.standard.object(forKey: "pasteAfterCopy") as? Bool ?? true
        retention = Retention(rawValue: UserDefaults.standard.string(forKey: "retention") ?? "") ?? .forever
        lastChangeCount = NSPasteboard.general.changeCount
        items = Self.load()
    }

    // MARK: - Derived

    var pinnedItems: [ClipItem] { items.filter { $0.pinned && $0.matches(query) } }
    var recentItems: [ClipItem] { items.filter { !$0.pinned && $0.matches(query) } }
    var visibleItems: [ClipItem] { pinnedItems + recentItems }

    func order(of id: UUID) -> Int? {
        selection.firstIndex(of: id).map { $0 + 1 }
    }

    // MARK: - Monitoring

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        timer?.tolerance = 0.1
        pruneExpired()
        Timer.scheduledTimer(withTimeInterval: 600, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.pruneExpired() }
        }
    }

    /// Drops unpinned clips older than the chosen history limit.
    func pruneExpired() {
        guard let maxAge = retention.maxAge else { return }
        let cutoff = Date().addingTimeInterval(-maxAge)
        let expired = items.filter { !$0.pinned && $0.date < cutoff }.map(\.id)
        guard !expired.isEmpty else { return }
        withAnimation(.spring(response: 0.4, dampingFraction: 0.85)) {
            items.removeAll { expired.contains($0.id) }
            selection.removeAll { expired.contains($0) }
            expired.forEach { thumbnails[$0] = nil }
        }
    }

    private func poll() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        capture()
    }

    private func capture() {
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.ignoredTypes) else { return }
        let source = NSWorkspace.shared.frontmostApplication

        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            insert(ClipItem(text: string, source: source)) { $0.text == string }
        } else if let data = imagePNGData(), data.count <= maxImageBytes {
            insert(ClipItem(imageData: data, source: source)) { $0.imageData == data }
        }
    }

    private func imagePNGData() -> Data? {
        if let png = pasteboard.data(forType: .png) { return png }
        guard let tiff = pasteboard.data(forType: .tiff),
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    private func insert(_ item: ClipItem, isDuplicate: (ClipItem) -> Bool) {
        withAnimation(.spring(response: 0.4, dampingFraction: 0.85)) {
            if let index = items.firstIndex(where: isDuplicate) {
                var existing = items.remove(at: index)
                existing.date = Date()
                existing.sourceAppName = item.sourceAppName ?? existing.sourceAppName
                existing.sourceBundleID = item.sourceBundleID ?? existing.sourceBundleID
                items.insert(existing, at: 0)
            } else {
                items.insert(item, at: 0)
                trim()
            }
        }
    }

    private func trim() {
        var unpinned = 0
        items.removeAll { item in
            guard !item.pinned else { return false }
            unpinned += 1
            if unpinned > maxItems {
                thumbnails[item.id] = nil
                selection.removeAll { $0 == item.id }
                return true
            }
            return false
        }
    }

    // MARK: - Selection

    func toggle(_ id: UUID) {
        withAnimation(.spring(response: 0.32, dampingFraction: 0.72)) {
            if let index = selection.firstIndex(of: id) {
                selection.remove(at: index)
            } else {
                selection.append(id)
            }
            highlightedID = id
        }
    }

    /// A click toggles selection; a second click on the same clip within the double-click interval
    /// undoes that toggle and copies just that clip.
    func tap(_ id: UUID) {
        let now = Date()
        if let last = lastTap, last.id == id, now.timeIntervalSince(last.time) < NSEvent.doubleClickInterval {
            lastTap = nil
            withAnimation(.spring(response: 0.32, dampingFraction: 0.72)) {
                selection = last.selectionBefore
            }
            if let item = items.first(where: { $0.id == id }) { copy(item) }
            return
        }
        lastTap = (id, now, selection)
        toggle(id)
    }

    func clearSelection() {
        withAnimation(.spring(response: 0.35, dampingFraction: 0.85)) {
            selection.removeAll()
        }
    }

    func moveHighlight(by delta: Int) {
        let visible = visibleItems
        guard !visible.isEmpty else { return }
        let current = visible.firstIndex { $0.id == highlightedID }
        let next: Int
        if let current {
            next = min(max(current + delta, 0), visible.count - 1)
        } else {
            next = delta > 0 ? 0 : visible.count - 1
        }
        withAnimation(.easeOut(duration: 0.12)) {
            highlightedID = visible[next].id
        }
    }

    func toggleHighlighted() {
        if let id = highlightedID ?? visibleItems.first?.id { toggle(id) }
    }

    // MARK: - Copying

    /// Return key: copies the selection in click order, or the highlighted item when nothing is selected.
    func copyPrimary() {
        if !selection.isEmpty {
            copySelection()
        } else if let id = highlightedID ?? visibleItems.first?.id,
                  let item = items.first(where: { $0.id == id }) {
            copy(item)
        }
    }

    func copySelection(transform: TextTransform? = nil) {
        let chosen = selection.compactMap { id in items.first { $0.id == id } }
        guard !chosen.isEmpty else { return }
        if chosen.count == 1 {
            copy(chosen[0], transform: transform)
            return
        }

        // Line breaks at the ends of a clip would otherwise leak into the joined result.
        let texts = chosen.compactMap(\.text).map { $0.trimmingCharacters(in: .newlines) }
        let images = chosen.compactMap(\.imageData).compactMap(NSImage.init(data:))
        var objects: [NSPasteboardWriting] = []
        if !texts.isEmpty {
            let joined = texts.joined(separator: separator.value)
            objects.append((transform?.apply(to: joined) ?? joined) as NSString)
        }
        objects.append(contentsOf: images)
        write(objects)
        finishCopy(message: "Copied \(chosen.count) items")
    }

    func copy(_ item: ClipItem, transform: TextTransform? = nil) {
        if let text = item.text {
            write([(transform?.apply(to: text) ?? text) as NSString])
        } else if let data = item.imageData, let image = NSImage(data: data) {
            write([image])
        }
        // Copying an older clip makes it the most recent one again.
        if !item.pinned, let index = items.firstIndex(of: item), index != 0 {
            withAnimation(.spring(response: 0.4, dampingFraction: 0.85)) {
                var moved = items.remove(at: index)
                moved.date = Date()
                items.insert(moved, at: 0)
            }
        }
        finishCopy(message: "Copied")
    }

    private func write(_ objects: [NSPasteboardWriting]) {
        pasteboard.clearContents()
        pasteboard.writeObjects(objects)
        // Our own writes should not show up as new history entries.
        lastChangeCount = pasteboard.changeCount
    }

    private func finishCopy(message: String) {
        withAnimation(.spring(response: 0.35, dampingFraction: 0.8)) {
            toast = message
        }
        let paste = pasteAfterCopy
        DispatchQueue.main.asyncAfter(deadline: .now() + (paste ? 0.35 : 0.55)) { [weak self] in
            if paste {
                self?.onRequestPaste?()
            } else {
                self?.onRequestClose?()
            }
        }
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.9) { [weak self] in
            guard let self else { return }
            self.toast = nil
            self.selection.removeAll()
        }
    }

    // MARK: - Editing

    func togglePin(_ id: UUID) {
        guard let index = items.firstIndex(where: { $0.id == id }) else { return }
        withAnimation(.spring(response: 0.4, dampingFraction: 0.85)) {
            items[index].pinned.toggle()
        }
    }

    func delete(_ id: UUID) {
        withAnimation(.spring(response: 0.35, dampingFraction: 0.85)) {
            if highlightedID == id {
                let visible = visibleItems
                if let index = visible.firstIndex(where: { $0.id == id }) {
                    let neighbor = index + 1 < visible.count ? index + 1 : index - 1
                    highlightedID = neighbor >= 0 ? visible[neighbor].id : nil
                }
            }
            items.removeAll { $0.id == id }
            selection.removeAll { $0 == id }
            thumbnails[id] = nil
        }
    }

    func deleteHighlighted() {
        if let id = highlightedID { delete(id) }
    }

    func clearHistory() {
        withAnimation(.spring(response: 0.4, dampingFraction: 0.85)) {
            let removed = items.filter { !$0.pinned }.map(\.id)
            items.removeAll { !$0.pinned }
            selection.removeAll { removed.contains($0) }
            removed.forEach { thumbnails[$0] = nil }
        }
    }

    func setLaunchAtLogin(_ enabled: Bool) {
        do {
            if enabled {
                try SMAppService.mainApp.register()
            } else {
                try SMAppService.mainApp.unregister()
            }
        } catch {
            NSLog("ClipStack: launch at login change failed: \(error)")
        }
        launchAtLogin = SMAppService.mainApp.status == .enabled
    }

    // MARK: - Popover lifecycle

    func didOpen() {
        pruneExpired()
        lastTap = nil
        query = ""
        highlightedID = visibleItems.first?.id
        openToken += 1
    }

    // MARK: - Images

    func thumbnail(for item: ClipItem) -> NSImage? {
        if let cached = thumbnails[item.id] { return cached }
        guard let data = item.imageData, let image = NSImage(data: data) else { return nil }
        thumbnails[item.id] = image
        return image
    }

    func appIcon(for bundleID: String?) -> NSImage? {
        guard let bundleID else { return nil }
        if let cached = appIcons[bundleID] { return cached }
        guard let url = NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleID) else { return nil }
        let icon = NSWorkspace.shared.icon(forFile: url.path)
        appIcons[bundleID] = icon
        return icon
    }

    // MARK: - Persistence

    private static var storeURL: URL {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("ClipStack", isDirectory: true)
        try? FileManager.default.createDirectory(at: base, withIntermediateDirectories: true)
        return base.appendingPathComponent("history.json")
    }

    private static func load() -> [ClipItem] {
        guard let data = try? Data(contentsOf: storeURL) else { return [] }
        return (try? JSONDecoder().decode([ClipItem].self, from: data)) ?? []
    }

    private func scheduleSave() {
        saveWork?.cancel()
        let snapshot = items
        let work = DispatchWorkItem {
            guard let data = try? JSONEncoder().encode(snapshot) else { return }
            try? data.write(to: Self.storeURL, options: .atomic)
        }
        saveWork = work
        DispatchQueue.global(qos: .utility).asyncAfter(deadline: .now() + 1, execute: work)
    }
}
