import AppKit
import Combine
import ServiceManagement
import SwiftUI

@MainActor
final class ClipboardStore: ObservableObject {
    @Published private(set) var items: [ClipItem] = [] {
        didSet { scheduleSave() }
    }
    /// Selected item ids, in the order they were clicked.
    @Published private(set) var selection: [UUID] = []
    @Published var query = "" {
        didSet { highlightedID = visibleItems.first?.id }
    }
    @Published var highlightedID: UUID?
    @Published var toast: String?
    @Published private(set) var openToken = 0
    @Published var separator: JoinSeparator {
        didSet { UserDefaults.standard.set(separator.rawValue, forKey: "separator") }
    }
    @Published var launchAtLogin: Bool = SMAppService.mainApp.status == .enabled
    @Published var pasteAfterCopy: Bool {
        didSet { UserDefaults.standard.set(pasteAfterCopy, forKey: "pasteAfterCopy") }
    }
    @Published var retention: Retention {
        didSet {
            UserDefaults.standard.set(retention.rawValue, forKey: "retention")
            pruneExpired()
        }
    }
    /// Leave out copies that look like passwords, API keys or tokens.
    @Published var skipSecrets: Bool {
        didSet { UserDefaults.standard.set(skipSecrets, forKey: "skipSecrets") }
    }
    @Published var shortcut: Shortcut {
        didSet { UserDefaults.standard.set(shortcut.rawValue, forKey: "shortcut") }
    }
    /// Set when the chosen shortcut couldn't be registered, usually because another app uses it.
    @Published var shortcutUnavailable = false
    /// False when the history couldn't be unlocked; the session then runs without saving.
    @Published private(set) var historySaved = true

    var onRequestClose: (() -> Void)?
    /// Demo mode (debug builds only) uses sample clips and never touches the real history or clipboard.
    private(set) var isDemo = false
    /// Closes the popover and pastes into the app that was in front before it opened.
    var onRequestPaste: (() -> Void)?

    private let maxItems = 200
    private let maxImageBytes = 8 * 1024 * 1024
    /// Longer copies (about 1 MB of text) are left out to keep the list and the history file fast.
    private let maxTextLength = 1_000_000
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private var saveWork: DispatchWorkItem?
    private let saveQueue = DispatchQueue(label: "ClipStack.save", qos: .utility)
    /// Pending close/paste and toast-clearing steps from the last copy, cancelled by the next one.
    private var copyFollowUps: [DispatchWorkItem] = []
    private var thumbnails: [UUID: NSImage] = [:]
    private var appIcons: [String: NSImage] = [:]
    private var lastTap: (id: UUID, time: Date, selectionBefore: [UUID])?
    /// While dragging: true selects the clips passed over, false deselects them.
    private var dragSelects: Bool?
    private var dragBaseSelection: [UUID] = []
    private var dragEndedAt: Date?

    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
    ]

    init() {
        separator = JoinSeparator(rawValue: UserDefaults.standard.string(forKey: "separator") ?? "") ?? .nothing
        pasteAfterCopy = UserDefaults.standard.object(forKey: "pasteAfterCopy") as? Bool ?? true
        retention = Retention(rawValue: UserDefaults.standard.string(forKey: "retention") ?? "") ?? .forever
        skipSecrets = UserDefaults.standard.object(forKey: "skipSecrets") as? Bool ?? true
        shortcut = Shortcut(rawValue: UserDefaults.standard.string(forKey: "shortcut") ?? "") ?? .controlCommandV
        lastChangeCount = NSPasteboard.general.changeCount
        switch HistoryFile.load() {
        case .loaded(let loaded):
            items = loaded
            if HistoryFile.hasPlainTextHistory { scheduleSave() }
        case .locked:
            historySaved = false
        }
    }

    // MARK: - Derived

    var pinnedItems: [ClipItem] { items.filter { $0.pinned && $0.matches(query) } }
    var recentItems: [ClipItem] { items.filter { !$0.pinned && $0.matches(query) } }
    var visibleItems: [ClipItem] { pinnedItems + recentItems }

    func order(of id: UUID) -> Int? {
        selection.firstIndex(of: id).map { $0 + 1 }
    }

    // MARK: - Monitoring

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        timer?.tolerance = 0.1
        pruneExpired()
        Timer.scheduledTimer(withTimeInterval: 600, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.pruneExpired() }
        }
    }

    /// Drops unpinned clips older than the chosen history limit.
    func pruneExpired() {
        guard let maxAge = retention.maxAge else { return }
        let cutoff = Date().addingTimeInterval(-maxAge)
        let expired = items.filter { !$0.pinned && $0.date < cutoff }.map(\.id)
        guard !expired.isEmpty else { return }
        withAnimation(.spring(response: 0.4, dampingFraction: 0.85)) {
            items.removeAll { expired.contains($0.id) }
            selection.removeAll { expired.contains($0) }
            expired.forEach { thumbnails[$0] = nil }
        }
    }

    private func poll() {
        guard !isDemo else { return }
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        capture()
    }

    private func capture() {
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.ignoredTypes) else { return }
        let source = NSWorkspace.shared.frontmostApplication

        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            guard string.utf16.count <= maxTextLength else { return }
            if skipSecrets, SecretDetector.looksSecret(string) { return }
            insert(ClipItem(text: string, source: source)) { $0.text == string }
        } else if let data = imagePNGData(), data.count <= maxImageBytes {
            insert(ClipItem(imageData: data, source: source)) { $0.imageData == data }
        }
    }

    private func imagePNGData() -> Data? {
        if let png = pasteboard.data(forType: .png) { return png }
        guard let tiff = pasteboard.data(forType: .tiff),
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    private func insert(_ item: ClipItem, isDuplicate: (ClipItem) -> Bool) {
        withAnimation(.spring(response: 0.4, dampingFraction: 0.85)) {
            if let index = items.firstIndex(where: isDuplicate) {
                var existing = items.remove(at: index)
                existing.date = Date()
                existing.sourceAppName = item.sourceAppName ?? existing.sourceAppName
                existing.sourceBundleID = item.sourceBundleID ?? existing.sourceBundleID
                items.insert(existing, at: 0)
            } else {
                items.insert(item, at: 0)
                trim()
            }
        }
    }

    private func trim() {
        var unpinned = 0
        items.removeAll { item in
            guard !item.pinned else { return false }
            unpinned += 1
            if unpinned > maxItems {
                thumbnails[item.id] = nil
                selection.removeAll { $0 == item.id }
                return true
            }
            return false
        }
    }

    // MARK: - Selection

    func toggle(_ id: UUID) {
        withAnimation(.spring(response: 0.32, dampingFraction: 0.72)) {
            if let index = selection.firstIndex(of: id) {
                selection.remove(at: index)
            } else {
                selection.append(id)
            }
            highlightedID = id
        }
    }

    /// A click toggles selection; a second click on the same clip within the double-click interval
    /// undoes that toggle and copies just that clip.
    func tap(_ id: UUID) {
        // The mouse-up that ends a drag also reaches the row as a click.
        if dragSelects != nil { return }
        if let dragEndedAt, Date().timeIntervalSince(dragEndedAt) < 0.3 { return }
        let now = Date()
        if let last = lastTap, last.id == id, now.timeIntervalSince(last.time) < min(NSEvent.doubleClickInterval, 0.35) {
            lastTap = nil
            withAnimation(.spring(response: 0.32, dampingFraction: 0.72)) {
                selection = last.selectionBefore
            }
            if let item = items.first(where: { $0.id == id }) { copy(item) }
            return
        }
        lastTap = (id, now, selection)
        toggle(id)
    }

    /// Called as a drag moves. `ids` are the clips between the drag's start and the pointer, nearest
    /// to the start first. Starting on a selected clip deselects; starting anywhere else selects.
    func drag(across ids: [UUID], startedOn startID: UUID?) {
        if dragSelects == nil {
            dragSelects = !(startID.map(selection.contains) ?? false)
            dragBaseSelection = selection
            lastTap = nil
        }
        guard let selecting = dragSelects else { return }
        let next = selecting
            ? dragBaseSelection + ids.filter { !dragBaseSelection.contains($0) }
            : dragBaseSelection.filter { !ids.contains($0) }
        guard next != selection else { return }
        withAnimation(.spring(response: 0.32, dampingFraction: 0.72)) {
            selection = next
        }
    }

    func endDrag() {
        guard dragSelects != nil else { return }
        dragSelects = nil
        dragBaseSelection = []
        dragEndedAt = Date()
    }

    /// Clicking empty space clears the selection, except for the click that ends a drag.
    func tapEmptySpace() {
        if dragSelects != nil { return }
        if let dragEndedAt, Date().timeIntervalSince(dragEndedAt) < 0.3 { return }
        clearSelection()
    }

    func clearSelection() {
        withAnimation(.spring(response: 0.35, dampingFraction: 0.85)) {
            selection.removeAll()
        }
    }

    func moveHighlight(by delta: Int) {
        let visible = visibleItems
        guard !visible.isEmpty else { return }
        let current = visible.firstIndex { $0.id == highlightedID }
        let next: Int
        if let current {
            next = min(max(current + delta, 0), visible.count - 1)
        } else {
            next = delta > 0 ? 0 : visible.count - 1
        }
        withAnimation(.easeOut(duration: 0.12)) {
            highlightedID = visible[next].id
        }
    }

    func toggleHighlighted() {
        if let id = highlightedID ?? visibleItems.first?.id { toggle(id) }
    }

    // MARK: - Copying

    /// Return key: copies the selection in click order, or the highlighted item when nothing is selected.
    func copyPrimary() {
        if !selection.isEmpty {
            copySelection()
        } else if let id = highlightedID ?? visibleItems.first?.id,
                  let item = items.first(where: { $0.id == id }) {
            copy(item)
        }
    }

    func copySelection(transform: TextTransform? = nil) {
        let chosen = selection.compactMap { id in items.first { $0.id == id } }
        guard !chosen.isEmpty else { return }
        if chosen.count == 1 {
            copy(chosen[0], transform: transform)
            return
        }

        let images = chosen.compactMap(\.imageData).compactMap(NSImage.init(data:))
        var objects: [NSPasteboardWriting] = []
        var message = "Copied \(chosen.count) items"
        if let joined = joinedText(of: chosen) {
            let text = transform?.apply(to: joined) ?? joined
            objects.append(text as NSString)
            message += " · \(Self.charCount(text))"
        }
        objects.append(contentsOf: images)
        write(objects)
        finishCopy(message: message)
    }

    /// Characters the selection's text will have once joined, or nil when only images are selected.
    /// Uses each clip's cached counts, so it stays cheap for long clips.
    var selectedCharCount: Int? {
        let texts = selection.compactMap { id in items.first { $0.id == id } }.filter { $0.text != nil }
        guard !texts.isEmpty else { return nil }
        if texts.count == 1 { return texts[0].charCount }
        return texts.reduce(0) { $0 + $1.joinedCharCount } + separator.value.count * (texts.count - 1)
    }

    private func joinedText(of chosen: [ClipItem]) -> String? {
        let texts = chosen.compactMap(\.text)
        guard !texts.isEmpty else { return nil }
        if texts.count == 1 { return texts[0] }
        // Line breaks at the ends of a clip would otherwise leak into the joined result.
        return texts.map { $0.trimmingCharacters(in: .newlines) }.joined(separator: separator.value)
    }

    /// Character count including spaces and line breaks.
    static func charCount(_ text: String) -> String {
        charCountLabel(text.count)
    }

    static func charCountLabel(_ count: Int) -> String {
        count == 1 ? "1 char" : "\(count) chars"
    }

    func copy(_ item: ClipItem, transform: TextTransform? = nil) {
        var message = "Copied"
        if let text = item.text {
            let output = transform?.apply(to: text) ?? text
            write([output as NSString])
            message += " · \(Self.charCount(output))"
        } else if let data = item.imageData, let image = NSImage(data: data) {
            write([image])
        }
        // Copying an older clip makes it the most recent one again.
        if !item.pinned, let index = items.firstIndex(of: item), index != 0 {
            withAnimation(.spring(response: 0.4, dampingFraction: 0.85)) {
                var moved = items.remove(at: index)
                moved.date = Date()
                items.insert(moved, at: 0)
            }
        }
        finishCopy(message: message)
    }

    private func write(_ objects: [NSPasteboardWriting]) {
        guard !isDemo else { return }
        pasteboard.clearContents()
        pasteboard.writeObjects(objects)
        // Our own writes should not show up as new history entries.
        lastChangeCount = pasteboard.changeCount
    }

    private func finishCopy(message: String) {
        // A new copy replaces the previous one's pending steps, so they can't clear its toast or selection.
        copyFollowUps.forEach { $0.cancel() }
        copyFollowUps = []
        withAnimation(.spring(response: 0.35, dampingFraction: 0.8)) {
            toast = message
        }
        let paste = pasteAfterCopy
        let reset = DispatchWorkItem { [weak self] in
            withAnimation(.spring(response: 0.35, dampingFraction: 0.85)) {
                self?.toast = nil
                self?.selection.removeAll()
            }
        }
        if isDemo {
            schedule(reset, after: 1.6)
            return
        }
        schedule(DispatchWorkItem { [weak self] in
            if paste {
                self?.onRequestPaste?()
            } else {
                self?.onRequestClose?()
            }
        }, after: paste ? 0.35 : 0.55)
        schedule(reset, after: 0.9)
    }

    private func schedule(_ work: DispatchWorkItem, after delay: TimeInterval) {
        copyFollowUps.append(work)
        DispatchQueue.main.asyncAfter(deadline: .now() + delay, execute: work)
    }

    // MARK: - Editing

    func togglePin(_ id: UUID) {
        guard let index = items.firstIndex(where: { $0.id == id }) else { return }
        withAnimation(.spring(response: 0.4, dampingFraction: 0.85)) {
            items[index].pinned.toggle()
        }
    }

    func delete(_ id: UUID) {
        withAnimation(.spring(response: 0.35, dampingFraction: 0.85)) {
            if highlightedID == id {
                let visible = visibleItems
                if let index = visible.firstIndex(where: { $0.id == id }) {
                    let neighbor = index + 1 < visible.count ? index + 1 : index - 1
                    highlightedID = neighbor >= 0 ? visible[neighbor].id : nil
                }
            }
            items.removeAll { $0.id == id }
            selection.removeAll { $0 == id }
            thumbnails[id] = nil
        }
    }

    func deleteHighlighted() {
        if let id = highlightedID { delete(id) }
    }

    func clearHistory() {
        withAnimation(.spring(response: 0.4, dampingFraction: 0.85)) {
            let removed = items.filter { !$0.pinned }.map(\.id)
            items.removeAll { !$0.pinned }
            selection.removeAll { removed.contains($0) }
            removed.forEach { thumbnails[$0] = nil }
        }
    }

    func setLaunchAtLogin(_ enabled: Bool) {
        do {
            if enabled {
                try SMAppService.mainApp.register()
            } else {
                try SMAppService.mainApp.unregister()
            }
        } catch {
            NSLog("ClipStack: launch at login change failed: \(error)")
        }
        launchAtLogin = SMAppService.mainApp.status == .enabled
    }

    // MARK: - Popover lifecycle

    func didOpen() {
        pruneExpired()
        lastTap = nil
        query = ""
        highlightedID = visibleItems.first?.id
        openToken += 1
    }

    // MARK: - Images

    func thumbnail(for item: ClipItem) -> NSImage? {
        if let cached = thumbnails[item.id] { return cached }
        guard let data = item.imageData, let image = NSImage(data: data) else { return nil }
        thumbnails[item.id] = image
        return image
    }

    func appIcon(for bundleID: String?) -> NSImage? {
        guard let bundleID else { return nil }
        if let cached = appIcons[bundleID] { return cached }
        guard let url = NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleID) else { return nil }
        let icon = NSWorkspace.shared.icon(forFile: url.path)
        appIcons[bundleID] = icon
        return icon
    }

    // MARK: - Persistence

    private func scheduleSave() {
        guard !isDemo, historySaved else { return }
        saveWork?.cancel()
        let snapshot = items
        let work = DispatchWorkItem {
            do {
                try HistoryFile.save(snapshot)
            } catch {
                NSLog("ClipStack: saving history failed: \(error)")
            }
        }
        saveWork = work
        saveQueue.asyncAfter(deadline: .now() + 1, execute: work)
    }

    /// Writes any pending change right away. Called when the app quits.
    func flushSave() {
        guard let saveWork, !saveWork.isCancelled else { return }
        saveWork.cancel()
        self.saveWork = nil
        guard !isDemo, historySaved else { return }
        let snapshot = items
        saveQueue.sync {
            try? HistoryFile.save(snapshot)
        }
    }
}

#if DEBUG
extension ClipboardStore {
    func loadDemoItems() {
        isDemo = true
        let samples: [(String, String, String, TimeInterval)] = [
            ("Hi team, here's the summary from today's sync:", "com.apple.mail", "Mail", 20),
            ("https://github.com/neul-lov/ClipStack", "com.apple.Safari", "Safari", 95),
            ("Ship v1.2 on Friday after QA sign-off.", "com.apple.Notes", "Notes", 300),
            ("brew install --cask neul-lov/tap/clipstack", "com.apple.Terminal", "Terminal", 900),
            ("Thanks for the quick review! 🙌", "com.apple.MobileSMS", "Messages", 2400),
            ("SELECT name, email FROM users WHERE active = 1;", "com.microsoft.VSCode", "Visual Studio Code", 5400),
        ]
        selection = []
        items = samples.map { text, bundleID, appName, age in
            var item = ClipItem(text: text, source: nil)
            item.sourceBundleID = bundleID
            item.sourceAppName = appName
            item.date = Date().addingTimeInterval(-age)
            return item
        }
    }

    func demoSelect(_ index: Int) {
        guard visibleItems.indices.contains(index) else { return }
        toggle(visibleItems[index].id)
    }
}
#endif
